mpi:
  path: '/home/gulhane.2/mvapich2-installation/nvidia/master_plus_cuda_11.7_gcc_10.3.0_new'
  include: '/home/gulhane.2/mvapich2-installation/nvidia/master_plus_cuda_11.7_gcc_10.3.0_new/include'

cuda:
  path: '/usr/local/cuda'
  include: '/usr/local/cuda/include'

nccl:
  path: '/home/gulhane.2/MCR_DL/nccl/build'
  include: '/home/gulhane.2/MCR_DL/nccl/build/include'