mpi:
  path: '/path/to/mpi/installation'
  include: '/path/to/mpi/installation/include'

cuda:
  path: '/usr/local/cuda'
  include: '/usr/local/cuda/include'

nccl:
  path: '/path/to/nccl/installation/build'
  include: '/path/to/nccl/installation/build/include'